import type { RegulatorySourceRegistryEntry } from "@/lib/regulatory/types";

export const REGULATORY_SOURCE_REGISTRY: RegulatorySourceRegistryEntry[] = [
  {
    source_id: "enforcements",
    display_name: "Enforcements",
    agency: "DOJ / FTC / DOL",
    category: "Federal Enforcement / Actions / Cases / OSHA",
    access_type: "api",
    base_url: "https://www.justice.gov/",
    api_docs_url: "https://www.justice.gov/developer",
    requires_api_key: false,
    supports_company_search: true,
    supports_entity_search: true,
    supports_address_search: false,
    supports_facility_search: true,
    supports_document_download: true,
    supports_date_filter: true,
    supports_docket_filter: true,
    supports_state_filter: true,
    supports_naics_sic_filter: false,
    default_page_size: 50,
    adapter_status: "working",
    priority: "high",
    notes:
      "Merged enforcement tab. Searches DOJ enforcement-related press releases, FTC Cases and Proceedings, and DOL / OSHA inspection-citation enforcement results in one table.",
  },
  {
    source_id: "litigation",
    display_name: "Litigation",
    agency: "CourtListener / PACER",
    category: "Federal Litigation / Dockets / RECAP / PACER",
    access_type: "api",
    base_url: "https://www.courtlistener.com/",
    api_docs_url: "https://courtlistener.com/help/api/rest/search",
    requires_api_key: true,
    env_key_name: "COURTLISTENER_API_TOKEN",
    supports_company_search: true,
    supports_entity_search: true,
    supports_address_search: false,
    supports_facility_search: false,
    supports_document_download: true,
    supports_date_filter: true,
    supports_docket_filter: true,
    supports_state_filter: false,
    supports_naics_sic_filter: false,
    default_page_size: 50,
    adapter_status: "working",
    priority: "high",
    notes:
      "Searches CourtListener / RECAP for federal litigation by company name. If PACER_USERNAME and PACER_PASSWORD are also configured, the tab adds PACER Case Locator party-search results too. PACER searches may incur PACER charges.",
  },
  {
    source_id: "epa_echo",
    display_name: "EPA ECHO",
    agency: "EPA",
    category: "Environmental / Compliance",
    access_type: "api",
    base_url: "https://echo.epa.gov/",
    api_docs_url: "https://echo.epa.gov/tools/web-services",
    requires_api_key: false,
    supports_company_search: true,
    supports_entity_search: true,
    supports_address_search: true,
    supports_facility_search: true,
    supports_document_download: true,
    supports_date_filter: true,
    supports_docket_filter: false,
    supports_state_filter: true,
    supports_naics_sic_filter: true,
    default_page_size: 25,
    adapter_status: "working",
    priority: "high",
    notes: "All Media facility search via ECHO REST (get_facilities / get_qid).",
  },
  {
    source_id: "epa_envirofacts",
    display_name: "EPA Envirofacts",
    agency: "EPA",
    category: "Environmental / Facility Data",
    access_type: "api",
    base_url: "https://enviro.epa.gov/",
    api_docs_url: "https://www.epa.gov/enviro/envirofacts-data-service-api",
    requires_api_key: false,
    supports_company_search: true,
    supports_entity_search: true,
    supports_address_search: true,
    supports_facility_search: true,
    supports_document_download: false,
    supports_date_filter: false,
    supports_docket_filter: false,
    supports_state_filter: true,
    supports_naics_sic_filter: true,
    default_page_size: 25,
    adapter_status: "working",
    priority: "medium",
    notes: "FRS facility site search via Envirofacts Data Service API (FRS_FACILITY_SITE / primary_name contains).",
  },
  {
    source_id: "fda_openfda",
    display_name: "FDA / openFDA",
    agency: "FDA",
    category: "Healthcare / Product / Recalls / Enforcement",
    access_type: "api",
    base_url: "https://api.fda.gov/",
    api_docs_url: "https://open.fda.gov/apis/",
    requires_api_key: false,
    env_key_name: "FDA_OPENFDA_API_KEY",
    supports_company_search: true,
    supports_entity_search: true,
    supports_address_search: false,
    supports_facility_search: true,
    supports_document_download: true,
    supports_date_filter: true,
    supports_docket_filter: false,
    supports_state_filter: false,
    supports_naics_sic_filter: false,
    default_page_size: 25,
    adapter_status: "working",
    priority: "high",
    notes: "Implements recall search first (enforcement/recall).",
  },
  {
    source_id: "cms_data",
    display_name: "CMS Data",
    agency: "CMS",
    category: "Healthcare Provider / Facility / Medicare",
    access_type: "api",
    base_url: "https://data.cms.gov/",
    api_docs_url: "https://npiregistry.cms.hhs.gov/",
    requires_api_key: false,
    supports_company_search: true,
    supports_entity_search: true,
    supports_address_search: true,
    supports_facility_search: true,
    supports_document_download: false,
    supports_date_filter: true,
    supports_docket_filter: false,
    supports_state_filter: true,
    supports_naics_sic_filter: false,
    default_page_size: 25,
    adapter_status: "working",
    priority: "medium",
    notes:
      "Uses the CMS NPI Registry plus CMS hospital enrollment, hospital ownership, hospital change-of-ownership, and skilled nursing facility ownership datasets tied to organization names.",
  },
  {
    source_id: "nhtsa",
    display_name: "NHTSA",
    agency: "NHTSA",
    category: "Auto / Vehicle Safety / Recalls / Complaints",
    access_type: "api",
    base_url: "https://data.transportation.gov/",
    api_docs_url: "https://vpic.nhtsa.dot.gov/api/",
    requires_api_key: false,
    supports_company_search: true,
    supports_entity_search: true,
    supports_address_search: false,
    supports_facility_search: false,
    supports_document_download: true,
    supports_date_filter: true,
    supports_docket_filter: false,
    supports_state_filter: false,
    supports_naics_sic_filter: false,
    default_page_size: 25,
    adapter_status: "working",
    priority: "high",
    notes: "Uses NHTSA's public DOT recalls-by-manufacturer dataset export, so no NHTSA_API_KEY is required.",
  },
  {
    source_id: "phmsa",
    display_name: "PHMSA",
    agency: "PHMSA",
    category: "Pipeline / Hazardous Materials Safety",
    access_type: "search_portal",
    base_url: "https://www.phmsa.dot.gov/data-and-statistics",
    requires_api_key: false,
    supports_company_search: true,
    supports_entity_search: true,
    supports_address_search: false,
    supports_facility_search: true,
    supports_document_download: false,
    supports_date_filter: true,
    supports_docket_filter: false,
    supports_state_filter: true,
    supports_naics_sic_filter: false,
    default_page_size: 25,
    adapter_status: "partial",
    priority: "medium",
    notes:
      "Returns targeted PHMSA public surfaces for incident bulk files, enforcement documents, and the operator-reporting portal; PHMSA still publishes most company-relevant data as bulk artifacts rather than a stable row API.",
  },
  {
    source_id: "ferc",
    display_name: "FERC",
    agency: "FERC",
    category: "Energy / Utility / Pipeline Proceedings",
    access_type: "search_portal",
    base_url: "https://elibrary.ferc.gov/",
    api_docs_url: "https://www.ferc.gov/data",
    requires_api_key: false,
    supports_company_search: true,
    supports_entity_search: true,
    supports_address_search: false,
    supports_facility_search: false,
    supports_document_download: true,
    supports_date_filter: true,
    supports_docket_filter: true,
    supports_state_filter: false,
    supports_naics_sic_filter: false,
    default_page_size: 25,
    adapter_status: "partial",
    priority: "low",
    notes:
      "Returns FERC company-registration / CID listing links plus eLibrary proceedings search, which is still portal-centric for document-level review.",
  },
  {
    source_id: "occ_institution_data",
    display_name: "OCC Institution Data",
    agency: "OCC",
    category: "Banks / OCC-Regulated Institutions / Enforcement",
    access_type: "api",
    base_url: "https://www.occ.gov/publications-and-resources/tools/occ-financial-institution-search/index-occ-financial-institution-search.html",
    api_docs_url: "https://api.occ.gov/",
    requires_api_key: false,
    supports_company_search: true,
    supports_entity_search: true,
    supports_address_search: false,
    supports_facility_search: false,
    supports_document_download: true,
    supports_date_filter: false,
    supports_docket_filter: false,
    supports_state_filter: false,
    supports_naics_sic_filter: false,
    default_page_size: 10,
    adapter_status: "working",
    priority: "high",
    notes: "Uses OCC's public institution autocomplete/search flow for OCC-regulated banks and savings associations.",
  },
  {
    source_id: "ffiec_cdr",
    display_name: "FFIEC CDR",
    agency: "FFIEC",
    category: "Bank Call Reports / UBPR / Reporter Panels",
    access_type: "bulk_data",
    base_url: "https://cdr.ffiec.gov/Public/PWS/PWSPage.aspx",
    api_docs_url: "https://cdr.ffiec.gov/public/pws/webservices/retrievalservice.asmx",
    requires_api_key: false,
    supports_company_search: true,
    supports_entity_search: true,
    supports_address_search: false,
    supports_facility_search: false,
    supports_document_download: true,
    supports_date_filter: true,
    supports_docket_filter: false,
    supports_state_filter: true,
    supports_naics_sic_filter: false,
    default_page_size: 25,
    adapter_status: "working",
    priority: "medium",
    notes:
      "Returns public institution-specific FFIEC report links plus real CDR bulk ZIP downloads for recent call-report periods. Authenticated FFIEC SOAP remains separate.",
  },
  {
    source_id: "eia",
    display_name: "EIA",
    agency: "EIA",
    category: "Energy Market Data",
    access_type: "api",
    base_url: "https://api.eia.gov/",
    api_docs_url: "https://www.eia.gov/opendata/",
    requires_api_key: true,
    env_key_name: "EIA_API_KEY",
    supports_company_search: false,
    supports_entity_search: false,
    supports_address_search: false,
    supports_facility_search: false,
    supports_document_download: false,
    supports_date_filter: true,
    supports_docket_filter: false,
    supports_state_filter: true,
    supports_naics_sic_filter: false,
    default_page_size: 25,
    adapter_status: "working",
    priority: "medium",
    notes: "Uses EIA route metadata and attempts live data previews for top matched dataset routes when available.",
  },
  {
    source_id: "sam_gov",
    display_name: "SAM.gov",
    agency: "GSA",
    category: "Federal Contracting / Exclusions / Opportunities",
    access_type: "api",
    base_url: "https://sam.gov/",
    api_docs_url: "https://open.gsa.gov/api/sam/",
    requires_api_key: true,
    env_key_name: "SAM_GOV_API_KEY",
    supports_company_search: true,
    supports_entity_search: true,
    supports_address_search: true,
    supports_facility_search: false,
    supports_document_download: true,
    supports_date_filter: true,
    supports_docket_filter: false,
    supports_state_filter: true,
    supports_naics_sic_filter: true,
    default_page_size: 25,
    adapter_status: "working",
    priority: "medium",
    notes: "Entity Management API v4 search with legal-name/DBA matching plus integrity-information enrichment when public fields are available.",
  },
  {
    source_id: "usaspending",
    display_name: "USAspending",
    agency: "Treasury",
    category: "Federal Awards / Contracts / Grants",
    access_type: "api",
    base_url: "https://api.usaspending.gov/",
    api_docs_url: "https://api.usaspending.gov/api",
    requires_api_key: false,
    supports_company_search: true,
    supports_entity_search: true,
    supports_address_search: false,
    supports_facility_search: false,
    supports_document_download: true,
    supports_date_filter: true,
    supports_docket_filter: false,
    supports_state_filter: true,
    supports_naics_sic_filter: true,
    default_page_size: 25,
    adapter_status: "working",
    priority: "high",
    notes: "Implements awards search with richer agency, UEI, outlay, and place-of-performance context when USAspending fields are available.",
  },
  {
    source_id: "fdic_bankfind",
    display_name: "FDIC BankFind",
    agency: "FDIC",
    category: "Banks / Financial Institutions",
    access_type: "api",
    base_url: "https://banks.data.fdic.gov/bankfind-suite/",
    api_docs_url: "https://banks.data.fdic.gov/docs/",
    requires_api_key: false,
    supports_company_search: true,
    supports_entity_search: true,
    supports_address_search: true,
    supports_facility_search: false,
    supports_document_download: false,
    supports_date_filter: false,
    supports_docket_filter: false,
    supports_state_filter: true,
    supports_naics_sic_filter: false,
    default_page_size: 25,
    adapter_status: "working",
    priority: "high",
    notes: "Uses the FDIC BankFind Suite institutions API with institution-name filters.",
  },
  {
    source_id: "cfpb_complaints",
    display_name: "CFPB Complaints",
    agency: "CFPB",
    category: "Consumer Finance Complaints",
    access_type: "api",
    base_url: "https://www.consumerfinance.gov/data-research/consumer-complaints/",
    api_docs_url: "https://cfpb.github.io/ccdb5-api/",
    requires_api_key: false,
    supports_company_search: true,
    supports_entity_search: true,
    supports_address_search: false,
    supports_facility_search: false,
    supports_document_download: false,
    supports_date_filter: true,
    supports_docket_filter: false,
    supports_state_filter: true,
    supports_naics_sic_filter: false,
    default_page_size: 25,
    adapter_status: "partial",
    priority: "medium",
    notes: "Uses CFPB complaint-database company suggestions and best-effort complaint retrieval when the API returns a manageable result set.",
  },
  {
    source_id: "finra",
    display_name: "FINRA",
    agency: "FINRA",
    category: "Broker-Dealer / Market / Regulatory Data",
    access_type: "manual",
    base_url: "https://brokercheck.finra.org/",
    requires_api_key: false,
    supports_company_search: true,
    supports_entity_search: true,
    supports_address_search: false,
    supports_facility_search: false,
    supports_document_download: false,
    supports_date_filter: false,
    supports_docket_filter: false,
    supports_state_filter: false,
    supports_naics_sic_filter: false,
    default_page_size: 25,
    adapter_status: "manual_only",
    priority: "low",
  },
  {
    source_id: "cftc",
    display_name: "CFTC",
    agency: "CFTC",
    category: "Futures / Derivatives / Enforcement / Market Data",
    access_type: "search_portal",
    base_url: "https://www.cftc.gov/",
    requires_api_key: false,
    supports_company_search: true,
    supports_entity_search: true,
    supports_address_search: false,
    supports_facility_search: false,
    supports_document_download: true,
    supports_date_filter: true,
    supports_docket_filter: false,
    supports_state_filter: false,
    supports_naics_sic_filter: false,
    default_page_size: 25,
    adapter_status: "manual_only",
    priority: "low",
  },
  {
    source_id: "federal_register",
    display_name: "Federal Register",
    agency: "Federal Register",
    category: "Rules / Notices / Proposed Rules",
    access_type: "api",
    base_url: "https://www.federalregister.gov/",
    api_docs_url: "https://www.federalregister.gov/developers/documentation/api/v1",
    requires_api_key: false,
    supports_company_search: true,
    supports_entity_search: true,
    supports_address_search: false,
    supports_facility_search: false,
    supports_document_download: true,
    supports_date_filter: true,
    supports_docket_filter: true,
    supports_state_filter: false,
    supports_naics_sic_filter: false,
    default_page_size: 25,
    adapter_status: "working",
    priority: "high",
  },
  {
    source_id: "regulations_gov",
    display_name: "Regulations.gov",
    agency: "Regulations.gov",
    category: "Rulemaking Dockets / Comments / Agency Documents",
    access_type: "api",
    base_url: "https://www.regulations.gov/",
    api_docs_url: "https://open.gsa.gov/api/regulationsgov/",
    requires_api_key: true,
    env_key_name: "REGULATIONS_GOV_API_KEY",
    supports_company_search: true,
    supports_entity_search: true,
    supports_address_search: false,
    supports_facility_search: false,
    supports_document_download: true,
    supports_date_filter: true,
    supports_docket_filter: true,
    supports_state_filter: false,
    supports_naics_sic_filter: false,
    default_page_size: 25,
    adapter_status: "working",
    priority: "high",
    notes: "Uses v4 document and docket search, with comment-window and attachment context when available. Falls back to DEMO_KEY for light search if no explicit key is set.",
  },
  {
    source_id: "ecfr",
    display_name: "eCFR",
    agency: "GPO / NARA",
    category: "Current Federal Regulations",
    access_type: "api",
    base_url: "https://www.ecfr.gov/",
    api_docs_url: "https://www.ecfr.gov/api/v1",
    requires_api_key: false,
    supports_company_search: false,
    supports_entity_search: false,
    supports_address_search: false,
    supports_facility_search: false,
    supports_document_download: true,
    supports_date_filter: false,
    supports_docket_filter: false,
    supports_state_filter: false,
    supports_naics_sic_filter: false,
    default_page_size: 25,
    adapter_status: "working",
    priority: "medium",
    notes: "Full-text search via ecfr.gov JSON API with pagination, citation-first display, and excerpt/context enrichment.",
  },
  {
    source_id: "osha",
    display_name: "OSHA",
    agency: "OSHA",
    category: "Workplace Safety / Inspections / Citations",
    access_type: "search_portal",
    base_url: "https://www.osha.gov/data",
    requires_api_key: false,
    supports_company_search: true,
    supports_entity_search: true,
    supports_address_search: true,
    supports_facility_search: true,
    supports_document_download: false,
    supports_date_filter: true,
    supports_docket_filter: false,
    supports_state_filter: true,
    supports_naics_sic_filter: true,
    default_page_size: 25,
    adapter_status: "working",
    priority: "medium",
    notes:
      "Scrapes OSHA's public establishment inspection search and inspection-detail pages, including case status, site details, and violation / penalty summaries when available.",
  },
  {
    source_id: "msha",
    display_name: "MSHA",
    agency: "MSHA",
    category: "Mine Safety / Violations / Accidents",
    access_type: "bulk_data",
    base_url: "https://www.msha.gov/data-reports",
    requires_api_key: false,
    supports_company_search: true,
    supports_entity_search: true,
    supports_address_search: false,
    supports_facility_search: true,
    supports_document_download: false,
    supports_date_filter: true,
    supports_docket_filter: false,
    supports_state_filter: true,
    supports_naics_sic_filter: false,
    default_page_size: 25,
    adapter_status: "not_started",
    priority: "medium",
  },
  {
    source_id: "fec",
    display_name: "FEC",
    agency: "FEC",
    category: "Campaign Finance / Political Contributions",
    access_type: "api",
    base_url: "https://api.open.fec.gov/",
    api_docs_url: "https://api.open.fec.gov/developers/",
    requires_api_key: true,
    env_key_name: "FEC_API_KEY",
    supports_company_search: true,
    supports_entity_search: true,
    supports_address_search: false,
    supports_facility_search: false,
    supports_document_download: true,
    supports_date_filter: true,
    supports_docket_filter: false,
    supports_state_filter: true,
    supports_naics_sic_filter: false,
    default_page_size: 25,
    adapter_status: "working",
    priority: "medium",
    notes: "OpenFEC committee and candidate search with top committee disbursement-recipient context when public endpoints respond.",
  },
  {
    source_id: "ofac",
    display_name: "OFAC / Treasury Sanctions",
    agency: "Treasury (OFAC)",
    category: "Sanctions / Blocked Parties",
    access_type: "bulk_data",
    base_url: "https://ofac.treasury.gov/sanctions-list-service",
    requires_api_key: false,
    supports_company_search: true,
    supports_entity_search: true,
    supports_address_search: true,
    supports_facility_search: false,
    supports_document_download: true,
    supports_date_filter: false,
    supports_docket_filter: false,
    supports_state_filter: false,
    supports_naics_sic_filter: false,
    default_page_size: 25,
    adapter_status: "working",
    priority: "high",
    notes:
      "Downloads the live OFAC SDN XML export and matches entity names / aliases locally, surfacing identifiers, birth/place-of-birth data, remarks, and vessel metadata when present.",
  },
  {
    source_id: "itc",
    display_name: "ITC",
    agency: "USITC",
    category: "Trade / Section 337 / Import Investigations",
    access_type: "manual",
    base_url: "https://www.usitc.gov/",
    requires_api_key: false,
    supports_company_search: true,
    supports_entity_search: true,
    supports_address_search: false,
    supports_facility_search: false,
    supports_document_download: true,
    supports_date_filter: true,
    supports_docket_filter: true,
    supports_state_filter: false,
    supports_naics_sic_filter: false,
    default_page_size: 25,
    adapter_status: "manual_only",
    priority: "low",
  },
  {
    source_id: "copyright",
    display_name: "U.S. Copyright Office",
    agency: "Copyright Office",
    category: "Copyright Records",
    access_type: "manual",
    base_url: "https://www.copyright.gov/",
    requires_api_key: false,
    supports_company_search: true,
    supports_entity_search: true,
    supports_address_search: false,
    supports_facility_search: false,
    supports_document_download: true,
    supports_date_filter: true,
    supports_docket_filter: false,
    supports_state_filter: false,
    supports_naics_sic_filter: false,
    default_page_size: 25,
    adapter_status: "manual_only",
    priority: "low",
  },
];

export function getRegulatorySource(sourceId: string) {
  return REGULATORY_SOURCE_REGISTRY.find((s) => s.source_id === sourceId) ?? null;
}

