/**
 * Roic v2 API field keys → traditional financial statement / metric names.
 * Unmapped keys fall back to Title Case from the key.
 */

const ROIC_LINE_LABELS: Record<string, string> = {
  // Income statement
  is_sales_revenue_turnover: "Revenue",
  is_sales_and_services_revenues: "Sales And Services Revenue",
  is_cogs: "Cost Of Goods Sold",
  is_cog_and_services_sold: "Cost Of Services Sold",
  is_gross_profit: "Gross Profit",
  is_operating_expn: "Operating Expenses",
  is_sg_and_a_expense: "Selling, General & Administrative",
  is_rd_expense: "Research & Development",
  is_other_operating_expenses: "Other Operating Expenses",
  is_oper_income: "Operating Income",
  is_nonop_income_loss: "Non-Operating Income (Loss)",
  is_net_interest_expense: "Net Interest Expense",
  is_int_expense: "Interest Expense",
  is_int_income: "Interest Income",
  is_other_nonop_income_loss: "Other Non-Operating Income (Loss)",
  is_pretax_income: "Pretax Income",
  is_inc_tax_exp: "Income Tax Expense",
  is_inc_bef_xo_item: "Income Before Extraordinary Items",
  is_xo_gl_net_of_tax: "Extraordinary Items (Net Of Tax)",
  is_extraord_items_and_acctg_chng: "Extraordinary Items And Accounting Changes",
  is_discontinued_operations: "Discontinued Operations",
  is_ni_including_minority_int_ratio: "Net Income Including Noncontrolling Interest",
  is_min_noncontrol_interest_credits: "Noncontrolling Interest",
  is_net_income: "Net Income",
  is_earn_for_common: "Net Income To Common",
  is_avg_num_sh_for_eps: "Average Shares (EPS)",
  is_sh_for_diluted_eps: "Diluted Shares",
  eps: "EPS (Basic)",
  eps_cont_ops: "EPS Continuing Operations (Basic)",
  diluted_eps: "EPS (Diluted)",
  dil_eps_cont_ops: "EPS Continuing Operations (Diluted)",
  ebitda: "EBITDA",
  ebitda_margin: "EBITDA Margin",
  ebita: "EBITA",
  ebit: "EBIT",
  gross_margin: "Gross Margin",
  oper_margin: "Operating Margin",
  profit_margin: "Net Margin",
  div_per_shr: "Dividends Per Share",
  is_depr_exp: "Depreciation Expense",
  // Balance sheet
  bs_c_and_ce_and_sti_detailed: "Cash And Short-Term Investments",
  bs_cash_near_cash_item: "Cash And Equivalents",
  bs_mkt_sec_other_st_invest: "Marketable Securities",
  bs_acct_note_rcv: "Accounts And Notes Receivable",
  bs_accts_rec_excl_notes_rec: "Accounts Receivable",
  bs_other_current_receivable: "Other Receivables",
  bs_inventories: "Inventories",
  bs_other_inv: "Inventory (Other)",
  bs_other_current_assets_detailed: "Other Current Assets",
  bs_cur_asset_report: "Total Current Assets",
  bs_net_fix_asset: "Net Property, Plant & Equipment",
  bs_gross_fix_asset: "Gross PP&E",
  bs_accum_depr: "Accumulated Depreciation",
  bs_lt_invest: "Long-Term Investments",
  bs_long_term_investments: "Long-Term Investments",
  bs_other_assets_def_chrg_other: "Other Assets",
  bs_disclosed_intangibles: "Intangible Assets (Disclosed)",
  bs_goodwill: "Goodwill",
  bs_other_intangible_assets_detailed: "Other Intangible Assets",
  bs_other_noncurrent_assets_detailed: "Other Noncurrent Assets",
  bs_tot_non_cur_asset: "Total Noncurrent Assets",
  bs_tot_asset: "Total Assets",
  bs_acct_payable_and_accruals_detailed: "Accounts Payable And Accruals",
  bs_acct_payable: "Accounts Payable",
  bs_accrual: "Accrued Expenses",
  bs_st_borrow: "Short-Term Borrowings",
  bs_short_term_debt_detailed: "Short-Term Debt",
  bs_other_current_liabs_sub_detailed: "Other Current Liabilities",
  bs_other_current_liabs_detailed: "Other Current Liabilities",
  bs_cur_liab: "Total Current Liabilities",
  bs_lt_borrow: "Long-Term Borrowings",
  bs_long_term_borrowings_detailed: "Long-Term Debt",
  bs_lt_capital_lease_obligations: "Capital Lease Obligations (LT)",
  bs_other_noncur_liabs_sub_detailed: "Other Noncurrent Liabilities",
  bs_accrued_liabilities: "Accrued Liabilities",
  bs_other_noncurrent_liabs_detailed: "Other Noncurrent Liabilities",
  bs_non_cur_liab: "Total Noncurrent Liabilities",
  bs_tot_liab: "Total Liabilities",
  bs_sh_cap_and_apic: "Common Stock And APIC",
  bs_common_stock: "Common Stock",
  bs_add_paid_in_cap: "Additional Paid-In Capital",
  bs_pure_retained_earnings: "Retained Earnings",
  bs_other_ins_res_to_shrhldr_eqy: "Other Equity Reserves",
  bs_eqty_bef_minority_int_detailed: "Equity Before Noncontrolling Interest",
  bs_minority_noncontrolling_interest: "Noncontrolling Interest",
  bs_total_equity: "Total Equity",
  bs_tot_liab_and_eqy: "Total Liabilities And Equity",
  bs_sh_out: "Shares Outstanding",
  bs_total_capital_leases: "Total Capital Leases",
  net_debt: "Net Debt",
  net_debt_to_shrhldr_eqty: "Net Debt To Equity",
  tce_ratio: "Tangible Common Equity Ratio",
  cur_ratio: "Current Ratio",
  cash_conversion_cycle: "Cash Conversion Cycle",
  // Cash flow
  cf_net_inc: "Net Income (CF Starting)",
  cf_depr_amort: "Depreciation And Amortization",
  cf_non_cash_items_detailed: "Non-Cash Items",
  cf_stock_based_compensation: "Stock-Based Compensation",
  cf_def_inc_tax: "Deferred Income Taxes",
  cf_asset_impairment_charge: "Asset Impairment",
  cf_other_non_cash_adj_less_detailed: "Other Non-Cash Adjustments",
  cf_chng_non_cash_work_cap: "Change In Working Capital",
  cf_acct_rcv_unbilled_rev: "Change In Receivables",
  cf_change_in_inventories: "Change In Inventories",
  cf_change_in_prepaid_assets: "Change In Prepaids",
  cf_change_in_accounts_payable: "Change In Accounts Payable",
  cf_inc_dec_in_ot_op_ast_liab_detail: "Other Operating Assets/Liabilities",
  cf_cash_from_oper: "Cash From Operations",
  cf_disp_fxd_and_intangibles_detailed: "Disposition Of PP&E And Intangibles",
  cf_disposal_of_fixed_prod_assets: "Proceeds From Asset Sales",
  cf_acquis_fxd_and_intang_detailed: "Capex (PP&E And Intangibles)",
  cf_purchase_of_fixed_prod_assets: "Purchase Of PP&E",
  cf_acquisition_of_intang_assets: "Acquisition Of Intangibles",
  cf_cap_expenditures: "Capital Expenditures",
  cf_net_chg_in_lt_invest_detailed: "Change In Long-Term Investments",
  cf_decr_invest: "Investment Proceeds",
  cf_incr_invest: "Investment Purchases",
  cf_nt_csh_rcvd_pd_for_acquis_div: "M&A Cash (Net)",
  cf_cash_for_acquis_subsidiaries: "Cash Paid For Acquisitions",
  cf_cash_for_divestitures: "Cash From Divestitures",
  cf_other_investing_act_detailed: "Other Investing Activities",
  cf_cash_from_inv_act: "Cash From Investing",
  cf_dvd_paid: "Dividends Paid",
  cf_nt_csh_proc_pymt_debt: "Net Debt Issuance (Repayment)",
  cf_proc_debt_and_capital_lease: "Proceeds From Debt And Leases",
  cf_pymt_debt_and_capital_lease: "Payments On Debt And Leases",
  cf_proc_fr_repurch_eqty_detailed: "Equity Repurchase Proceeds",
  cf_decr_cap_stock: "Share Repurchases",
  cf_other_financing_act_excl_fx: "Other Financing Activities",
  cf_cash_from_fin_act: "Cash From Financing",
  cf_effect_foreign_exchanges: "FX Effect On Cash",
  cf_net_chng_cash: "Net Change In Cash",
  cf_free_cash_flow: "Free Cash Flow",
  cf_free_cash_flow_firm: "Free Cash Flow (Firm)",
  free_cash_flow_equity: "Free Cash Flow To Equity",
  free_cash_flow_per_sh: "Free Cash Flow Per Share",
  cash_flow_to_net_inc: "Cash Flow To Net Income",
  cf_net_cash_paid_for_aquis: "Net Cash Paid For Acquisitions",
  // Credit ratios (representative)
  short_and_long_term_debt: "Total Debt",
  tot_debt_to_ebitda: "Total Debt To EBITDA",
  net_debt_to_ebitda: "Net Debt To EBITDA",
  total_debt_to_ebit: "Total Debt To EBIT",
  net_debt_to_ebit: "Net Debt To EBIT",
  ebitda_to_interest_expn: "EBITDA To Interest",
  ebitda_les_cap_expend_to_int_exp: "EBITDA Less Capex To Interest",
  oper_inc_to_int_exp: "Operating Income To Interest",
  com_eqy_to_tot_asset: "Common Equity To Total Assets",
  lt_debt_to_tot_eqy: "Long-Term Debt To Equity",
  lt_debt_to_tot_cap: "Long-Term Debt To Capital",
  lt_debt_to_tot_asset: "Long-Term Debt To Assets",
  tot_debt_to_tot_eqy: "Total Debt To Equity",
  tot_debt_to_tot_cap: "Total Debt To Capital",
  tot_debt_to_tot_asset: "Total Debt To Assets",
  net_debt_to_capital: "Net Debt To Capital",
  cap_expend_ratio: "Capex Ratio",
  // Liquidity
  cash_ratio: "Cash Ratio",
  quick_ratio: "Quick Ratio",
  cfo_to_avg_current_liabilities: "CFO To Avg Current Liabilities",
  cash_flow_to_tot_liab: "Cash Flow To Total Liabilities",
  altman_z_score: "Altman Z-Score",
  // Working capital
  acct_rcv_turn: "Accounts Receivable Turnover",
  acct_rcv_days: "Days Sales Outstanding",
  invent_turn: "Inventory Turnover",
  invent_days: "Days Inventory Outstanding",
  accounts_payable_turnover: "Accounts Payable Turnover",
  accounts_payable_turnover_days: "Days Payable Outstanding",
  inv_to_cash_days: "Inventory To Cash Days",
  // Enterprise value & multiples
  enterprise_value: "Enterprise Value",
  diluted_ev: "Diluted Enterprise Value",
  bs_tot_cap: "Total Capital",
  total_debt_to_ev: "Total Debt To EV",
  ev_to_ttm_sales: "EV To TTM Sales",
  ev_to_ttm_ebitda: "EV To TTM EBITDA",
  ev_to_ttm_ebit: "EV To TTM EBIT",
  ev_to_ttm_cash_flow_firm: "EV To TTM Cash Flow (Firm)",
  ev_to_ttm_free_cash_flow_firm: "EV To TTM FCF (Firm)",
  ev_to_sh_out: "EV Per Share",
  ttm_net_sales: "TTM Net Sales",
  ttm_ebitda: "TTM EBITDA",
  ttm_oper_inc: "TTM Operating Income",
  ttm_cash_flow_firm: "TTM Cash Flow (Firm)",
  ttm_free_cash_flow_firm: "TTM Free Cash Flow (Firm)",
  average_ev_to_ttm_sales: "Average EV To TTM Sales",
  high_ev_to_ttm_sales: "High EV To TTM Sales",
  low_ev_to_ttm_sales: "Low EV To TTM Sales",
  avg_ev_to_ttm_ebitda: "Average EV To TTM EBITDA",
  high_ev_to_ttm_ebitda: "High EV To TTM EBITDA",
  low_ev_to_ttm_ebitda: "Low EV To TTM EBITDA",
  average_ev_to_ttm_ebit: "Average EV To TTM EBIT",
  high_ev_to_ttm_ebit: "High EV To TTM EBIT",
  low_ev_to_ttm_ebit: "Low EV To TTM EBIT",
  average_enterprise_value: "Average Enterprise Value",
  high_enterprise_value: "High Enterprise Value",
  low_enterprise_value: "Low Enterprise Value",
  // Per share
  revenue_per_sh: "Revenue Per Share",
  ebitda_per_sh: "EBITDA Per Share",
  oper_inc_per_sh: "Operating Income Per Share",
  cash_flow_per_sh: "Cash Flow Per Share",
  cash_st_investments_per_sh: "Cash And ST Investments Per Share",
  book_val_per_sh: "Book Value Per Share",
  tang_book_val_per_sh: "Tangible Book Value Per Share",
};

function titleCaseWords(raw: string): string {
  const small = new Set(["and", "or", "of", "to", "in", "for", "the", "a", "an", "on", "at", "vs", "per"]);
  return raw
    .split(/\s+/)
    .filter(Boolean)
    .map((w, i) => {
      const lower = w.toLowerCase();
      if (i > 0 && small.has(lower)) return lower;
      if (/^q[1-4]$/i.test(w)) return w.toUpperCase();
      return w.charAt(0).toUpperCase() + w.slice(1).toLowerCase();
    })
    .join(" ");
}

/** Traditional display label for a Roic metric key. */
export function getRoicLineItemLabel(key: string): string {
  const mapped = ROIC_LINE_LABELS[key];
  if (mapped) return mapped;
  const spaced = key.replace(/_/g, " ");
  return titleCaseWords(spaced);
}
