/**
 * Golden regression targets for {@link extractDebtFootnote} / {@link extractDebtCapitalTables}.
 * Rows are placeholders until each filing is downloaded and headings verified manually.
 */
export type DebtFootnoteGoldenFixture = {
  id: string;
  category: string;
  formType: "10-K" | "10-Q";
  cik: string;
  accessionNumber: string;
  filingDate: string;
  /** Manually verified debt note heading text (plain). */
  goldenDebtNoteHeading: string;
  /** Optional strings that must appear in the primary extract when confidence is High or Medium. */
  goldenBodyMustInclude?: string[];
  status: "pending_capture" | "ready";
};

/** Minimum 50 scenarios covering varied titles and edge cases (populate accession + golden text before CI gating). */
export const DEBT_FOOTNOTE_GOLDEN_FIXTURES: DebtFootnoteGoldenFixture[] = [
  {
    id: "debt-title-generic",
    category: 'Note titled "Debt"',
    formType: "10-K",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000000",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "Note X. Debt",
    status: "pending_capture",
  },
  {
    id: "borrowings-title",
    category: 'Note titled "Borrowings"',
    formType: "10-K",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000001",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "Borrowings",
    status: "pending_capture",
  },
  {
    id: "financing-arrangements",
    category: 'Note titled "Financing Arrangements"',
    formType: "10-K",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000002",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "Financing Arrangements",
    status: "pending_capture",
  },
  {
    id: "long-term-debt-finance-leases",
    category: '"Long-Term Debt and Finance Lease Obligations"',
    formType: "10-K",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000003",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "Long-Term Debt and Finance Lease Obligations",
    status: "pending_capture",
  },
  {
    id: "convertible-notes",
    category: "Convertible notes",
    formType: "10-K",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000004",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "Convertible Notes",
    status: "pending_capture",
  },
  {
    id: "securitization-debt",
    category: "Securitization debt",
    formType: "10-K",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000005",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "Securitization Debt",
    status: "pending_capture",
  },
  {
    id: "no-material-debt",
    category: "Immaterial / no debt note",
    formType: "10-K",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000006",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "(none — expect Low or Not Found)",
    status: "pending_capture",
  },
  {
    id: "debt-inside-fair-value",
    category: "Debt inside Fair Value note",
    formType: "10-K",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000007",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "Fair Value Measurements",
    status: "pending_capture",
  },
  {
    id: "debt-inside-commitments",
    category: "Debt inside Commitments",
    formType: "10-K",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000008",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "Commitments and Contingencies",
    status: "pending_capture",
  },
  {
    id: "messy-inline-xbrl",
    category: "Messy inline XBRL headings",
    formType: "10-K",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000009",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "Debt",
    status: "pending_capture",
  },
  {
    id: "large-mdanda-debt-prose",
    category: "Heavy MD&A borrowings prose (negative control)",
    formType: "10-K",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000010",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "(must not substitute MD&A for Notes)",
    status: "pending_capture",
  },
  {
    id: "10q-standard",
    category: "10-Q standard Notes clip",
    formType: "10-Q",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000011",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "Debt",
    status: "pending_capture",
  },
  {
    id: "10q-condensed-notes-header",
    category: "10-Q condensed notes header variant",
    formType: "10-Q",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000012",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "Debt",
    status: "pending_capture",
  },
  {
    id: "credit-facility-title",
    category: 'Note titled "Credit Facility"',
    formType: "10-K",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000013",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "Credit Facility",
    status: "pending_capture",
  },
  {
    id: "notes-payable-title",
    category: 'Note titled "Notes Payable"',
    formType: "10-K",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000014",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "Notes Payable",
    status: "pending_capture",
  },
  {
    id: "industrials-capital-structure",
    category: "Industrials — senior secured / unsecured mix",
    formType: "10-K",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000015",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "Debt",
    status: "pending_capture",
  },
  {
    id: "reits-mortgage-debt",
    category: "REIT mortgage debt",
    formType: "10-K",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000016",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "Debt",
    status: "pending_capture",
  },
  {
    id: "banks-deposits-not-debt",
    category: "Bank — deposits vs borrowings (negative control)",
    formType: "10-K",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000017",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "(verify borrowings vs deposits)",
    status: "pending_capture",
  },
  {
    id: "utilities-regulated-debt",
    category: "Utilities borrowings",
    formType: "10-K",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000018",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "Debt",
    status: "pending_capture",
  },
  {
    id: "broken-note-heading-table-anchor",
    category: "Broken heading — recovered via table anchors",
    formType: "10-K",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000019",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "(nonstandard heading)",
    status: "pending_capture",
  },
  {
    id: "exhibit-index-proximity",
    category: "Exhibit index proximity guardrail",
    formType: "10-K",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000020",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "Debt",
    status: "pending_capture",
  },
  {
    id: "risk-factors-proximity",
    category: "Risk factors proximity guardrail",
    formType: "10-K",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000021",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "Debt",
    status: "pending_capture",
  },
  {
    id: "multi-currency-debt",
    category: "Multi-currency debt tables",
    formType: "10-K",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000022",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "Debt",
    status: "pending_capture",
  },
  {
    id: "short-term-debt-only",
    category: "Short-term borrowings emphasis",
    formType: "10-Q",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000023",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "Debt",
    status: "pending_capture",
  },
  {
    id: "finance-lease-heavy",
    category: "Finance lease obligations alongside debt",
    formType: "10-K",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000024",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "Debt and Finance Lease Obligations",
    status: "pending_capture",
  },
  {
    id: "bridge-loan-facility",
    category: "Bridge loan / acquisition debt",
    formType: "10-K",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000025",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "Debt",
    status: "pending_capture",
  },
  {
    id: "lines-of-credit-title",
    category: 'Note titled "Lines of Credit"',
    formType: "10-K",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000026",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "Lines of Credit",
    status: "pending_capture",
  },
  {
    id: "commercial-paper-program",
    category: "Commercial paper program",
    formType: "10-K",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000027",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "Debt",
    status: "pending_capture",
  },
  {
    id: "medium-term-notes",
    category: "Medium-term notes program",
    formType: "10-K",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000028",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "Debt",
    status: "pending_capture",
  },
  {
    id: "asset-based-lending",
    category: "ABL / asset-based loan",
    formType: "10-K",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000029",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "Debt",
    status: "pending_capture",
  },
  {
    id: "subsidiary-guarantees",
    category: "Subsidiary guarantees / guarantors schedule",
    formType: "10-K",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000030",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "Debt",
    status: "pending_capture",
  },
  {
    id: "fair-value-option-debt",
    category: "Debt measured at fair value",
    formType: "10-K",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000031",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "(fair value debt instrument)",
    status: "pending_capture",
  },
  {
    id: "related-party-debt",
    category: "Related-party borrowings",
    formType: "10-K",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000032",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "Related Party Transactions",
    status: "pending_capture",
  },
  {
    id: "variable-interest-entities-debt",
    category: "VIE consolidated debt",
    formType: "10-K",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000033",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "Variable Interest Entities",
    status: "pending_capture",
  },
  {
    id: "factored-receivables-debt",
    category: "Receivables securitization / factoring",
    formType: "10-K",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000034",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "Debt",
    status: "pending_capture",
  },
  {
    id: "foreign-subsidiary-debt",
    category: "Foreign subsidiary borrowings",
    formType: "10-K",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000035",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "Debt",
    status: "pending_capture",
  },
  {
    id: "capitalized-interest-debt",
    category: "Debt with capitalized interest table",
    formType: "10-K",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000036",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "Debt",
    status: "pending_capture",
  },
  {
    id: "debt-covenants-only-note",
    category: "Debt covenants disclosed outside titled Debt note",
    formType: "10-K",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000037",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "(verify split vs liquidity)",
    status: "pending_capture",
  },
  {
    id: "registration-statement-inline-xbrl",
    category: "Dense inline XBRL S-1 crossover",
    formType: "10-K",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000038",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "Debt",
    status: "pending_capture",
  },
  {
    id: "workiva-long-notes-document",
    category: "Very long Workiva-style Notes HTML",
    formType: "10-K",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000039",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "Debt",
    status: "pending_capture",
  },
  {
    id: "dual-column-debt-rollforward",
    category: "Dual-column debt rollforward table",
    formType: "10-Q",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000040",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "Debt",
    status: "pending_capture",
  },
  {
    id: "debt-extinguishment-gains-losses",
    category: "Debt extinguishment gains/losses disclosure",
    formType: "10-K",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000041",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "Debt",
    status: "pending_capture",
  },
  {
    id: "interest-rate-swaps-debt",
    category: "Debt hedged with interest-rate swaps",
    formType: "10-K",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000042",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "Derivative Instruments",
    status: "pending_capture",
  },
  {
    id: "government-backed-loans",
    category: "Government guaranteed borrowings",
    formType: "10-K",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000043",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "Debt",
    status: "pending_capture",
  },
  {
    id: "project-finance-debt",
    category: "Non-recourse project finance debt",
    formType: "10-K",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000044",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "Debt",
    status: "pending_capture",
  },
  {
    id: "restated-debt-note-number-shift",
    category: "Restatement shifts note numbering",
    formType: "10-K",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000045",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "(note number shift)",
    status: "pending_capture",
  },
  {
    id: "shell-company-minimal-debt",
    category: "Shell / SPAC minimal borrowings",
    formType: "10-Q",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000046",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "(thin debt)",
    status: "pending_capture",
  },
  {
    id: "debt-inside-supplemental-cash-flow",
    category: "Debt table inside supplemental cash flows",
    formType: "10-K",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000047",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "(negative control)",
    status: "pending_capture",
  },
  {
    id: "footnotes-table-heavy-no-heading-debt",
    category: "Schedule headings without Note title Debt",
    formType: "10-K",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000048",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "(nonstandard)",
    status: "pending_capture",
  },
  {
    id: "multi-tranche-senior-notes",
    category: "Multiple senior note tranches same indenture",
    formType: "10-K",
    cik: "0000000000",
    accessionNumber: "PENDING-0000000049",
    filingDate: "PENDING",
    goldenDebtNoteHeading: "Debt",
    status: "pending_capture",
  },
];
