// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { resolve } from "node:path";
import { defineConfig } from "prisma/config";

// `import "dotenv/config"` only loads `.env`. Next.js loads `.env.local`; Prisma CLI does not,
// so migrate/generate would keep using a stale URL (e.g. old Neon) if it only lived in `.env.local`.
config({ path: resolve(process.cwd(), ".env") });
config({ path: resolve(process.cwd(), ".env.local"), override: true });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
