import path from "path";
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "node",
    include: [
      "src/lib/egg-hoc-chat/**/*.test.ts",
      "src/lib/ratings-link-search/**/*.test.ts",
      "src/lib/regulatory/**/*.test.ts",
      "src/lib/news/**/*.test.ts",
      "src/lib/daily-news/**/*.test.ts",
      "src/lib/brokerResearch/**/*.test.ts",
      "src/lib/analystActivity/**/*.test.ts",
      "src/lib/xSearch/**/*.test.ts",
      "src/lib/researchFinder/**/*.test.ts",
      "src/lib/substack/**/*.test.ts",
      "src/lib/reddit/**/*.test.ts",
      "src/lib/reddit/*.test.ts",
      "src/lib/xbrl-ai-consolidation/**/*.test.ts",
      "src/lib/xbrl-saved-history/**/*.test.ts",
      "src/lib/llm-temperature.test.ts",
      "src/lib/llm-api-error-report.test.ts",
      "src/lib/sec-edgar.test.ts",
      "src/lib/sec/filingIndex.test.ts",
      "src/lib/sec-filing-exhibits.test.ts",
      "src/lib/exhibit21GridExtract.test.ts",
      "src/lib/buildPublicRecordsProfileFromSec.test.ts",
      "src/lib/company-workspace-key.test.ts",
      "src/lib/company-prompt-labels.test.ts",
      "src/lib/subsidiary-name-hints.test.ts",
      "src/lib/debt-map/**/*.test.ts",
      "src/lib/secDebtFootnoteExtract.test.ts",
      "src/lib/debt-footnote-display.test.ts",
      "src/lib/xbrl-compiler-display.test.ts",
      "src/lib/secDebtFootnote/**/*.test.ts",
      "src/lib/sec-ixbrl-mdna-boundaries.test.ts",
      "src/lib/sec-ixbrl-mdna-tables.test.ts",
      "src/lib/sec-narrative-table-display.test.ts",
      "src/lib/adjusted-ebitda-display.test.ts",
      "src/lib/revenue-drivers-boundaries.test.ts",
      "src/lib/sec-ixbrl-narrative-self-diagnostics.test.ts",
      "src/lib/sec-filing-financials.test.ts",
      "src/lib/sec-filing-financials-parse-amount.test.ts",
      "src/lib/sec-statement-locator/**/*.test.ts",
      "src/lib/sec-ixbrl-inline-cell.test.ts",
      "src/lib/sec-ixbrl-face-display.test.ts",
      "src/lib/period-financials-roic.test.ts",
      "src/lib/period-financials-period-cache.test.ts",
      "src/lib/presentations/discovery/presentation-discovery.test.ts",
      "src/lib/sec-ixbrl-face-extract.test.ts",
      "src/lib/sec-xbrl-as-presented.test.ts",
      "src/lib/sec-xbrl-balance-sheet-dedupe.test.ts",
      "src/lib/sec-xbrl-balance-sheet-reorder.test.ts",
      "src/lib/sec-xbrl-balance-sheet-shares.test.ts",
      "src/lib/sec-xbrl-display-normalize.test.ts",
      "src/lib/sec-xbrl-income-statement-numeric.test.ts",
      "src/lib/sec-xbrl-export-validation.test.ts",
      "src/lib/sec-self-diagnostic-checklist.test.ts",
      "src/lib/sec-xbrl-is-presentation-filter.test.ts",
      "src/lib/creditMemo/**/*.test.ts",
      "src/lib/bulk-credit-doc-match.test.ts",
      "src/lib/bulk-earnings-package.test.ts",
      "src/lib/bulk-update-preflight.test.ts",
      "src/lib/research-tab-output-style.test.ts",
      "src/lib/extract-xlsx-from-api-text.test.ts",
      "src/lib/user-data-export-consolidated-text.test.ts",
      "src/lib/extract-credit-doc-save-label.test.ts",
    ],
  },
  resolve: {
    alias: { "@": path.resolve(__dirname, "./src") },
  },
});
