import type { BrokerDefinition } from "../types";

/**
 * One entry per supported broker. Add a row here (and env mapping in config) to extend coverage.
 */
export const BROKER_REGISTRY_ENTRIES: BrokerDefinition[] = [
  {
    id: "jpmorgan",
    name: "J.P. Morgan",
    enabledByDefault: true,
    domains: ["jpmorgan.com", "jpmorganaccess.com"],
    aliases: ["JPM", "JP Morgan", "J.P. Morgan"],
    searchPatterns: ["J.P. Morgan", "JP Morgan research"],
    urlHints: ["/research", "/insights", "jpmorgan"],
  },
  {
    id: "goldman",
    name: "Goldman Sachs",
    enabledByDefault: true,
    domains: ["goldmansachs.com", "gs.com"],
    aliases: ["Goldman", "Goldman Sachs"],
    searchPatterns: ["Goldman Sachs research"],
    urlHints: ["/insights", "/research", "goldman"],
  },
  {
    id: "morgan_stanley",
    name: "Morgan Stanley",
    enabledByDefault: true,
    domains: ["morganstanley.com"],
    aliases: ["Morgan Stanley", "MS Research"],
    searchPatterns: ["Morgan Stanley research"],
    urlHints: ["/ideas", "/research", "morganstanley"],
  },
  {
    id: "ubs",
    name: "UBS",
    enabledByDefault: true,
    domains: ["ubs.com"],
    aliases: ["UBS Investment Bank", "UBS Research"],
    searchPatterns: ["UBS research"],
    urlHints: ["/research", "/insights"],
  },
  {
    id: "bofa",
    name: "BofA Securities",
    enabledByDefault: true,
    domains: ["bofa.com", "business.bofa.com", "bankofamerica.com", "ml.com"],
    aliases: ["Bank of America", "BofA", "Merrill Lynch"],
    searchPatterns: ["BofA Global Research", "Bank of America research"],
    urlHints: ["/research", "bofaml", "business.bofa"],
  },
  {
    id: "jefferies",
    name: "Jefferies",
    enabledByDefault: true,
    domains: ["jefferies.com"],
    aliases: ["Jefferies LLC"],
    searchPatterns: ["Jefferies research"],
    urlHints: ["/research", "/insights"],
  },
  {
    id: "barclays",
    name: "Barclays",
    enabledByDefault: true,
    domains: ["barclays.com", "research.barclays.com"],
    aliases: ["Barclays Investment Bank"],
    searchPatterns: ["Barclays research"],
    urlHints: ["/research", "barclays"],
  },
  {
    id: "citi",
    name: "Citi",
    enabledByDefault: true,
    domains: ["citi.com", "citigroup.com"],
    aliases: ["Citigroup", "Citi Research"],
    searchPatterns: ["Citi research"],
    urlHints: ["/research", "citigroup"],
  },
  {
    id: "deutsche_bank",
    name: "Deutsche Bank",
    enabledByDefault: true,
    domains: ["db.com"],
    aliases: ["Deutsche Bank Research", "DB Research"],
    searchPatterns: ["Deutsche Bank research"],
    urlHints: ["/research", "dbresearch"],
  },
  {
    id: "wells_fargo",
    name: "Wells Fargo Securities",
    enabledByDefault: true,
    domains: ["wellsfargo.com"],
    aliases: ["Wells Fargo"],
    searchPatterns: ["Wells Fargo research"],
    urlHints: ["/research", "wellsfargo"],
  },
  {
    id: "evercore",
    name: "Evercore ISI",
    enabledByDefault: true,
    domains: ["evercore.com", "evercoreisi.com"],
    aliases: ["Evercore"],
    searchPatterns: ["Evercore ISI"],
    urlHints: ["/insights", "/research"],
  },
  {
    id: "bmo",
    name: "BMO Capital Markets",
    enabledByDefault: true,
    domains: ["bmo.com", "bmocm.com"],
    aliases: ["BMO"],
    searchPatterns: ["BMO Capital Markets research"],
    urlHints: ["/research", "bmo"],
  },
  {
    id: "rbc",
    name: "RBC Capital Markets",
    enabledByDefault: true,
    domains: ["rbccm.com", "rbc.com"],
    aliases: ["RBC", "RBC CM"],
    searchPatterns: ["RBC Capital Markets research"],
    urlHints: ["/research", "rbccm"],
  },
  {
    id: "btig",
    name: "BTIG",
    enabledByDefault: true,
    domains: ["btig.com"],
    aliases: ["BTIG Research"],
    searchPatterns: ["BTIG research"],
    urlHints: ["/research", "btig"],
  },
  {
    id: "guggenheim",
    name: "Guggenheim Securities",
    enabledByDefault: true,
    domains: ["guggenheimpartners.com", "guggenheimsecurities.com"],
    aliases: ["Guggenheim"],
    searchPatterns: ["Guggenheim research"],
    urlHints: ["/research", "guggenheim"],
  },
  {
    id: "morningstar",
    name: "Morningstar",
    enabledByDefault: true,
    domains: ["morningstar.com"],
    aliases: ["Morningstar Equity Research"],
    searchPatterns: ["Morningstar analyst"],
    urlHints: ["/articles", "/research", "morningstar"],
  },
  {
    id: "oppenheimer",
    name: "Oppenheimer",
    enabledByDefault: true,
    domains: ["oppenheimer.com", "opco.com"],
    aliases: ["Oppenheimer & Co"],
    searchPatterns: ["Oppenheimer research"],
    urlHints: ["/research", "oppenheimer"],
  },
  {
    id: "bernstein",
    name: "Bernstein",
    enabledByDefault: true,
    domains: ["bernstein.com", "alliancebernstein.com"],
    aliases: ["AllianceBernstein", "Sanford C. Bernstein"],
    searchPatterns: ["Bernstein research"],
    urlHints: ["/research", "bernstein"],
  },
  {
    id: "stifel",
    name: "Stifel",
    enabledByDefault: true,
    domains: ["stifel.com"],
    aliases: ["Stifel Nicolaus"],
    searchPatterns: ["Stifel research"],
    urlHints: ["/research", "stifel"],
  },
  {
    id: "scotiabank",
    name: "Scotiabank GBM",
    enabledByDefault: true,
    domains: ["scotiabank.com", "gbcm.scotiabank.com"],
    aliases: ["Scotia", "BNS"],
    searchPatterns: ["Scotiabank research"],
    urlHints: ["/research", "scotiabank"],
  },
  {
    id: "td_cowen",
    name: "TD Cowen",
    enabledByDefault: true,
    domains: ["cowen.com", "td.com", "tdsecurities.com"],
    aliases: ["Cowen", "TD Securities"],
    searchPatterns: ["TD Cowen research", "Cowen research"],
    urlHints: ["/research", "cowen", "tdsecurities"],
  },
  {
    id: "truist",
    name: "Truist Securities",
    enabledByDefault: true,
    domains: ["truist.com"],
    aliases: ["Truist"],
    searchPatterns: ["Truist research"],
    urlHints: ["/insights", "/research"],
  },
  {
    id: "canaccord",
    name: "Canaccord Genuity",
    enabledByDefault: true,
    domains: ["canaccordgenuity.com", "cgf.com"],
    aliases: ["Canaccord"],
    searchPatterns: ["Canaccord Genuity research"],
    urlHints: ["/research", "canaccord"],
  },
  {
    id: "needham",
    name: "Needham & Company",
    enabledByDefault: true,
    domains: ["needhamco.com"],
    aliases: ["Needham"],
    searchPatterns: ["Needham research"],
    urlHints: ["/research", "needham"],
  },
  {
    id: "benchmark",
    name: "The Benchmark Company",
    enabledByDefault: true,
    domains: ["benchmarkcompany.com"],
    aliases: ["Benchmark Company"],
    searchPatterns: ["Benchmark Company research"],
    urlHints: ["/research", "benchmark"],
  },
];
