/** Default role columns for facility matrices (matches product spec). */
export const ENTITY_MAPPER_V2_ROLE_COLUMNS: readonly string[] = [
  "Borrower",
  "Issuer",
  "Co-Issuer",
  "Guarantor",
  "Parent Guarantor",
  "Subsidiary Guarantor",
  "Note Guarantor",
  "Loan Party / Credit Party",
  "Obligor",
  "Grantor / Pledgor",
  "Collateral Party",
  "Restricted Subsidiary",
  "Unrestricted Subsidiary",
  "Excluded Subsidiary",
  "Non-Guarantor Restricted Subsidiary",
  "Material Subsidiary",
  "Immaterial Subsidiary",
  "Foreign Subsidiary",
  "Domestic Subsidiary",
  "Designated Subsidiary",
  "Securitization / Receivables Subsidiary",
  "Captive Insurance / SPV",
  "Intermediate Holdings",
  "Parent / Holdings",
  "OpCo",
  "Finance Subsidiary",
  "Other Role",
];
