/**
 * Extra industry tokens derived from SEC SIC (4-digit normalized).
 * Improves trade-publication matching when company names/descriptions are terse or ambiguous.
 * Keys: 3-digit (preferred) or 2-digit fallback — see https://www.osha.gov/data/sic-manual
 */

const THREE_DIGIT: Record<string, string> = {
  "011": "crop farming agricultural production cash grain",
  "131": "crude petroleum natural gas exploration production extraction",
  "138": "oil gas field services drilling well services",
  "152": "residential building construction general contractors housing",
  "162": "heavy construction highways bridges civil engineering infrastructure",
  "171": "plumbing heating air conditioning mechanical contractors",
  "173": "electrical contractors wiring installation",
  "201": "meat packing slaughterhouse protein processing",
  "208": "beverage bottling soft drink brewing distillery",
  "283": "pharmaceutical medicinal drug biological vaccine preparation",
  "291": "petroleum refining refinery downstream",
  "308": "plastic products molded packaging industrial plastic",
  "331": "steel blast furnace mill metal manufacturing",
  "353": "construction mining machinery heavy equipment manufacturing",
  "357": "computer office equipment hardware manufacturing",
  "361": "electrical transmission distribution apparatus grid equipment",
  "367": "semiconductor electronic component integrated circuit manufacturing",
  "371": "motor vehicle passenger car truck oem automotive assembly manufacturing",
  "372": "aircraft aerospace parts aviation manufacturing defense",
  "381": "navigation instruments medical optical measurement equipment",
  "384": "surgical medical dental instruments device manufacturing",
  "401": "railroad freight line transportation rail",
  "421": "trucking motor freight long haul logistics carrier",
  "451": "scheduled air transportation airline passenger cargo aviation",
  "481": "telephone communications telecom wireless wireline broadband",
  "483": "radio television broadcasting cable network media",
  "491": "electric power generation transmission distribution utility",
  "492": "natural gas transmission distribution pipeline utility",
  "495": "sanitary sewer waste disposal environmental services",
  "502": "wholesale durable goods distribution",
  "531": "department stores retail merchandising",
  "541": "grocery supermarkets food retail convenience stores",
  "553": "auto home supply retail hardware building materials",
  "561": "apparel clothing accessory retail stores",
  "573": "consumer electronics computer retail software retail",
  "581": "eating drinking places restaurant foodservice dining",
  "591": "drug stores pharmacy retail health retail",
  "596": "nonstore retail catalog mail order ecommerce direct selling",
  "602": "national commercial bank banking deposits lending",
  "614": "personal credit short term finance lending",
  "621": "security brokers dealers investment banking capital markets",
  "628": "investment advisory asset management wealth services",
  "631": "life health accident insurance underwriting carriers",
  "633": "property casualty insurance fire marine liability underwriting",
  "651": "real estate operators lessors apartment office retail reit",
  "679": "investment offices holding companies trusts",
  "701": "hotels motels lodging hospitality resort casino",
  "731": "advertising agencies marketing communications media buying",
  "737": "computer programming software saas cloud data processing it services",
  "738": "business support services security equipment rental staffing",
  "751": "passenger car automobile rental leasing without driver truck rental fleet",
  "783": "motion picture production distribution theatrical exhibition",
  "801": "physicians clinics medical offices outpatient care",
  "806": "hospitals inpatient surgical psychiatric medical facility",
  "809": "medical diagnostic laboratories outpatient allied health",
  "871": "engineering architectural surveying professional services",
};

const TWO_DIGIT: Record<string, string> = {
  "01": "agriculture crop livestock farming",
  "02": "agriculture animal livestock dairy poultry",
  "07": "agricultural services crop soil",
  "08": "forestry timber logging",
  "09": "fishing hunting trapping",
  "10": "metal mining precious industrial",
  "12": "coal mining bituminous lignite",
  "13": "oil gas extraction petroleum",
  "14": "nonmetallic minerals quarry",
  "15": "construction building general contractors",
  "16": "heavy construction engineering contractors",
  "17": "construction special trade contractors",
  "20": "food kindred products processing",
  "21": "tobacco products manufacturing",
  "22": "textile mill products fabric",
  "23": "apparel finished textile products",
  "24": "lumber wood furniture millwork",
  "25": "furniture fixtures manufacturing",
  "26": "paper allied products pulp packaging",
  "27": "printing publishing newspaper",
  "28": "chemicals allied products pharmaceutical plastics",
  "29": "petroleum refining coal products",
  "30": "rubber miscellaneous plastic products",
  "31": "leather leather products",
  "32": "stone clay glass cement concrete",
  "33": "primary metal industries steel aluminum",
  "34": "fabricated metal products industrial",
  "35": "industrial machinery equipment manufacturing",
  "36": "electronic electrical equipment manufacturing",
  "37": "transportation equipment motor vehicle aircraft ship",
  "38": "instruments medical optical measurement",
  "39": "miscellaneous manufacturing",
  "40": "railroad transportation freight",
  "42": "motor freight trucking warehousing logistics",
  "44": "water transportation marine shipping",
  "45": "air transportation airline cargo",
  "46": "pipelines petroleum transportation",
  "47": "transportation services transit taxi",
  "48": "communications telecom telephone cable broadcast",
  "49": "electric gas sanitary utility power grid",
  "50": "wholesale trade durable nondurable distribution",
  "51": "wholesale trade nondurable goods",
  "52": "building materials hardware garden retail",
  "53": "general merchandise retail stores",
  "54": "food grocery retail stores",
  "55": "automotive dealers gasoline retail",
  "56": "apparel accessory retail",
  "57": "furniture home furnishings retail",
  "58": "eating drinking places restaurant retail",
  "59": "miscellaneous retail",
  "60": "banking depository institutions credit",
  "61": "nondepository credit institutions finance",
  "62": "security commodity brokers dealers exchanges",
  "63": "insurance carriers agents brokers",
  "64": "insurance agents brokers services",
  "65": "real estate operators lessors",
  "67": "real estate investment trusts holding offices",
  "70": "hotels lodging camps recreation",
  "72": "personal services laundry repair",
  "73": "business services computer rental programming",
  "75": "automotive repair rental leasing services parking",
  "76": "miscellaneous repair services",
  "78": "motion picture amusement recreation services",
  "79": "amusement recreation sports entertainment",
  "80": "health services hospitals medical dental",
  "81": "legal services",
  "82": "educational services schools",
  "83": "social services membership organizations",
  "87": "engineering accounting research management services",
  "89": "miscellaneous services",
};

/**
 * Returns lowercase synonym tokens to append to the publication matching context.
 */
export function expandSicContext(normalizedSicDigits: string): string {
  const d = normalizedSicDigits.replace(/\D/g, "").padStart(4, "0").slice(0, 4);
  if (!d || d === "0000") return "";
  const d3 = d.slice(0, 3);
  const d2 = d.slice(0, 2);
  const exact = THREE_DIGIT[d3];
  if (exact) return exact;
  const broad = TWO_DIGIT[d2];
  return broad ?? "";
}
